import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const datatype = localFont({
  src: [{ path: "../public/fonts/Datatype-Regular.woff2", weight: "400" }],
  variable: "--font-datatype",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${datatype.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
