import type { HexItem } from "@/lib/types";

export const SKILLS: HexItem[] = [
  {
    id: "ansible",
    name: "Ansible",
    description:
      "One of the most powerful tools for systems administrators. Deploying, provisioning, and managing infrastructure is made easy using YAML playbooks. I have used playbooks to spin up hosting environments for internal use.",
    type: "skills",
    accent: "#ee0000",
    image: "/skills/ansible.svg",
    level: "beginner",
  },
  {
    id: "apache",
    name: "Apache HTTP Server",
    description:
      "Most commonly used in shared hosting environments, my experience with Apache HTTP Server includes configuring .htaccess files for URL rewriting, access control, and performance optimizations, as well as managing virtual hosts.",
    type: "skills",
    accent: "#d22128",
    image: "/skills/apache.svg",
    level: "knowledgeable",
  },
  {
    id: "beaver-builder",
    name: "Beaver Builder",
    description:
      "I have been worked extensively with Beaver Builder, an industry-leading WordPress page builder plugin with a visual drag-and-drop interface, for more than 5 years. My work includes the full Beaver Builder ecosystem: core plugin, Beaver Themer, and child theme framework.",
    type: "skills",
    level: "expert",
  },
  {
    id: "css",
    name: "Cascading Style Sheets",
    description:
      "CSS is one of my favorite web development disciplines as it gives the web its flavor. I have extensive experience with tried and true techniques: cross-browser compatibility, efficient selectors, CSS Grid, Flexbox, variables, and more. The specification is always evolving and I look forward to rolling out new features as they are adopted.",
    type: "skills",
    accent: "#663399",
    image: "/skills/css.svg",
    level: "expert",
  },
  {
    id: "gsap",
    name: "Greensock Animation Platform",
    description:
      "A powerful JS library for creating high-performance, complex, and cross-browser animations. My experience with GSAP has mostly been limited to enhancing static webpages with interactive animation elements, but this tool is capable of so much more. Whenever the opportunity to elevate a project with animation presents itself, GSAP is my go-to solution.",
    type: "skills",
    accent: "#0AE448",
    image: "/skills/gsap.svg",
    level: "beginner",
  },
  {
    id: "github",
    name: "Github",
    description:
      "Github is the preferred source code repository platform and has evolved over the years to include a wide range of features. My experience just barely scratches the surface of what Github can do, but I have been putting the effort of learning more about how to improve my workflow with Actions, Copilot, and Codespaces.",
    type: "skills",
    accent: "#181717",
    image: "/skills/github.svg",
    level: "beginner",
  },
  {
    id: "html",
    name: "HTML",
    description: "The foundational language of browsers. Not much else to say.",
    type: "skills",
    accent: "#E34F26",
    image: "/skills/html5.svg",
    level: "expert",
  },
  {
    id: "indesign",
    name: "Indesign",
    description:
      "My knowledge of Indesign is primarily focused on adapting existing visual elements for the web: Fine-tuning anchor points, cleaning up any artifacts, and optimizing designs for use in webfonts or animations.",
    type: "skills",
    level: "beginner",
  },
  {
    id: "javascript",
    name: "JavaScript",
    description:
      "One of the most controversial scripting languages and the backbone of the interactive web. Manipulating the DOM, handling events, and adding effects that CSS hasn't caught up with yet are some of the examples of how I have used JS.",
    type: "skills",
    accent: "#F7DF1E",
    image: "/skills/javascript.svg",
    level: "expert",
  },
  {
    id: "jquery",
    name: "jQuery",
    description:
      "A once ubiquitous extension of JavaScript that used to make DOM manipulation and event handling easier across browsers. It is still used in legacy projects and WordPress, and I have had to go back and rework jQuery code to be up to date with the best practices.",
    type: "skills",
    accent: "#0769AD",
    image: "/skills/jquery.svg",
    level: "expert",
  },
  {
    id: "json",
    name: "JSON",
    description:
      "A lightweight data-interchange format that is the gold standard of modern APIs and data storage.",
    type: "skills",
    accent: "#000000",
    image: "/skills/json.svg",
    level: "expert",
  },
  {
    id: "lighthouse",
    name: "Lighthouse",
    description:
      "Essential tool for auditing site performance, accessibility, and best SEO practices. ",
    type: "skills",
    accent: "#F44B21",
    image: "/skills/lighthouse.svg",
    level: "knowledgeable",
  },
  {
    id: "mysql",
    name: "MySQL",
    description: "Relational database management system",
    type: "skills",
    accent: "#4479A1",
    image: "/skills/mysql.svg",
    level: "knowledgeable",
  },
  {
    id: "nginx",
    name: "Nginx",
    description: "Web server software",
    type: "skills",
    accent: "#009639",
    image: "/skills/nginx.svg",
    level: "beginner",
  },
  {
    id: "linux",
    name: "Linux",
    description: "Unix-like operating systems",
    type: "skills",
    accent: "#FCC624",
    image: "/skills/linux.svg",
    level: "knowledgeable",
  },
  {
    id: "nodejs",
    name: "NodeJS",
    description: "JavaScript runtime environment",
    type: "skills",
    accent: "#5FA04E",
    image: "/skills/nodedotjs.svg",
    level: "knowledgeable",
  },
  {
    id: "photoshop",
    name: "Photoshop",
    description: "Image editing software",
    type: "skills",
    level: "knowledgeable",
  },
  {
    id: "php",
    name: "PHP",
    description: "Server-side scripting language",
    type: "skills",
    accent: "#777BB4",
    image: "/skills/php.svg",
    level: "expert",
  },
  {
    id: "python",
    name: "Python",
    description: "High-level programming language",
    type: "skills",
    accent: "#3776AB",
    image: "/skills/python.svg",
    level: "beginner",
  },
  {
    id: "typescript",
    name: "TypeScript",
    description: "Superset of JavaScript with static typing",
    type: "skills",
    accent: "#3178C6",
    image: "/skills/typescript.svg",
    level: "knowledgeable",
  },
  {
    id: "nextjs",
    name: "NextJS",
    description: "React framework for server-rendered applications",
    type: "skills",
    accent: "#000000",
    image: "/skills/nextdotjs.svg",
    level: "beginner",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    description: "Relational database management system",
    type: "skills",
    accent: "#4169E1",
    image: "/skills/postgresql.svg",
    level: "beginner",
  },
  {
    id: "gatsby",
    name: "Gatsby",
    description: "React-based framework for building static websites",
    type: "skills",
    accent: "#663399",
    image: "/skills/gatsby.svg",
    level: "beginner",
  },
  {
    id: "claude",
    name: "Claude",
    description: "AI assistant developed by Anthropic",
    type: "skills",
    accent: "#000000",
    image: "/skills/claude.svg",
    level: "knowledgeable",
  },
  {
    id: "react",
    name: "React",
    description: "JavaScript library for building user interfaces",
    type: "skills",
    accent: "#61DAFB",
    image: "/skills/react.svg",
    level: "knowledgeable",
  },
  {
    id: "responsive",
    name: "Responsive Web Design",
    description: "Design approach for optimal viewing on various devices",
    type: "skills",
    level: "expert",
  },
  {
    id: "rest",
    name: "REST APIs",
    description: "Representational State Transfer",
    type: "skills",
    level: "knowledgeable",
  },
  {
    id: "seo",
    name: "SEO",
    description: "Search Engine Optimization",
    type: "skills",
    level: "knowledgeable",
  },
  {
    id: "svg",
    name: "Scalable Vector Graphics",
    description: "I really enjoy using SVGs to make high-quality graphics that can be easily scaled, styled, and animated in real-time. Their versatility makes them ideal for pretty much every scenario where graphics are needed on the web. Depending on the project, SVGs can be packaged with the HTML, served as separate files, or converted into an icon font.",
    type: "skills",
    accent: "#FFB13B",
    image: "/skills/svg.svg",
    level: "expert",
  },
  {
    id: "roots",
    name: "Roots",
    description: "An emerging, open-source WordPress stack that brings much needed modernization to WordPress development. Trellis, Bedrock, and Sage are promising tools and I have been experimenting with them in personal projects but haven't had the opportunity to use them in a production environment yet.",
    type: "skills",
    image: "/skills/roots.svg",
    level: "beginner",
  },
  {
    id: "vscode",
    name: "VSCode",
    description: "Source code editor",
    type: "skills",
    level: "knowledgeable",
  },
  {
    id: "wordpress",
    name: "WordPress",
    description: "I have been working with WordPress for my entire professional career and have produced too many projects to list. My knowledge of WordPress covers the full stack: server configuration, database management, and theme and plugin development. WordPress is generally preferred since most clients are familiar with it and I work on tailoring each environment to fit the specifications of the project.",
    type: "skills",
    image: "/skills/wordpress.svg",
    level: "expert",
  },
];
