import type { HexItem } from "@/lib/types";

export const WORKS: HexItem[] = [
  {
    id: "amicus",
    name: "Amicus Legal Group",
    type: "works",
    image: "/works/alg.webp",
    url: "https://www.amicuslegalgroup.com",
  },
  {
    id: "briskman",
    name: "Briskman, Briskman & Greenberg",
    type: "works",
    image: "/works/bbg.webp",
    url: "https://www.briskmanandbriskman.com",
  },
  {
    id: "begley",
    name: "Begley Law Group",
    type: "works",
    image: "/works/begley.webp",
    url: "https://www.begleylawgroup.com",
  },
  {
    id: "brill",
    name: "Brill Legal Group",
    type: "works",
    image: "/works/brill.webp",
    url: "https://www.brill-legal.com",
  },
  {
    id: "chandler-ross",
    name: "Chandler Ross Law",
    type: "works",
    image: "/works/ch.webp",
    url: "https://www.chandlerrosslaw.com",
  },
  {
    id: "custom-legal-marketing",
    name: "Custom Legal Marketing",
    type: "works",
    image: "/works/clm.webp",
    url: "https://www.custom.legal",
  },
  {
    id: "hale",
    name: "Hale Law Firm",
    type: "works",
    image: "/works/hlf.webp",
    url: "https://www.thehalelawfirm.com",
  },
  {
    id: "legal-help-for-veterans",
    name: "Legal Help for Veterans",
    type: "works",
    image: "/works/lhfv.webp",
    url: "https://www.legalhelpforveterans.com",
  },
  {
    id: "lapayowker",
    name: "Lapayowker Jet Counsel",
    type: "works",
    image: "/works/ljc.webp",
  },
  {
    id: "littman-krooks",
    name: "Littman Krooks",
    type: "works",
    image: "/works/lk.webp",
    url: "https://www.littmankrooks.com",
  },
  {
    id: "leonard",
    name: "Leonard Law Firm",
    type: "works",
    image: "/works/llf.webp",
    url: "https://www.lawleonard.com",
  },
  {
    id: "myphillylawyer",
    name: "MyPhillyLawyer",
    type: "works",
    image: "/works/mpl.webp",
    url: "https://www.myphillylawyer.com",
  },
  {
    id: "melaragno-placidi",
    name: "Melaragno Placidi",
    type: "works",
    image: "/works/mpp.webp",
    url: "https://www.erieinjuryattorney.com",
  },
  {
    id: "strong-advocates",
    name: "Strong Advocates",
    type: "works",
    image: "/works/sa.webp",
    url: "https://www.strongadvocates.com",
  },
  {
    id: "schuelke-law",
    name: "Schuelke Law",
    type: "works",
    image: "/works/slf.webp",
    url: "https://www.civtrial.com",
  },
  {
    id: "sommers-schwartz",
    name: "Sommers Schwartz",
    type: "works",
    image: "/works/spc.webp",
    url: "https://www.sommerspc.com",
  },
];
